# Gemfile to help setting up the initial development environment
source 'https://rubygems.org'

gem 'calabash-android', '~> 0.5.14'

# Gems that will only be used with the computer is a Mac
group :mac_os do
  # Remenber to fix the calabash-cucumber version. The update of this gem is
  # a proccess that you need to update the Calabash Server on your iOS
  # application code. So I suggest doing the update manually
  gem 'calabash-cucumber', '~> 0.16.4'
end
