devNatan:
  xcworkspace: "/Users/natan.ximenes/Documents/Workspace/iOS-Workspace/estacio-mobile-ios/Estacio.xcworkspace"
  scheme: Estacio-cal
  configuration: Debug
  destination: "platform=iOS Simulator,name=iPhone 6"
  export_path: "/Users/natan.ximenes/Documents/Workspace/QA-Workspace/estacio-mobile-qa/ios-output"

devNatanSpecial:
  xcworkspace: "/Users/natan.ximenes/Documents/Workspace/iOS-Workspace/estacio-mobile-ios/Estacio.xcworkspace"
  scheme: Estacio-cal
  configuration: Special
  destination: "platform=iOS Simulator,name=iPhone 6"
  export_path: "/Users/natan.ximenes/Documents/Workspace/QA-Workspace/estacio-mobile-qa/ios-output"

devIngrid:
  xcworkspace: "/Users/ingrid.andrade/Documents/Workspace/iOS-Workspace/estacio-mobile-ios/Estacio.xcworkspace"
  scheme: Estacio-cal
  configuration: Debug
  destination: "platform=iOS Simulator,name=iPhone 6"
  export_path: "/Users/ingrid.andrade/Documents/Workspace/QA-Workspace/estacio-mobile-qa/ios-output"

jenkins:
  xcworkspace: <%= ENV['WORKSPACE']%>/Project.xcworkspace
  scheme: TargetName
  configuration: Debug
  export_path: <%= ENV['WORKSPACE']%>/releases/normal
