dev:
  xcworkspace: "Path_to_the_xcworkspace_folder"
  scheme: TargetName
  configuration: Debug
  export_path: "Path_to_export_app_folder"

jenkins:
  xcworkspace: <%= ENV['WORKSPACE']%>/Project.xcworkspace
  scheme: TargetName
  configuration: Debug
  export_path: <%= ENV['WORKSPACE']%>/releases/normal
